# Generated by Django 5.2.4 on 2025-07-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('Block', 'Block'), ('Accident', 'Accident'), ('Pothole', 'Pothole'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
