# Generated by Django 5.2.4 on 2025-07-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=200)),
                ('to_place', models.CharField(max_length=200)),
                ('from_lat', models.FloatField()),
                ('from_lng', models.FloatField()),
                ('to_lat', models.FloatField()),
                ('to_lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='level',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='trafficreport',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
